[package]
name = "dev-syn/permissions"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
TestEZ = "roblox/testez@0.4.1"
[place]
shared-packages = "game.ReplicatedStorage.Dependencies"